version: 2
jobs:
  build:
    # to speed up Dockers builds turn on layer caching
    # which is a paid CircleCI feature
    # https://circleci.com/docs/2.0/docker-layer-caching/
    machine:
      docker_layer_caching: false
    steps:
    - checkout
    - run: mkdir -p media/routechoices-maps/maps/
    - run: ./dc build
    - run: ./dc up -d
    - run: ./da migrate
    - run: ./da collectstatic
    - run: ./da createcachetable
    - run: ./dc restart web 
    - run: timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false
    - run: ./da test
    - run: ./da reset_db_for_tests
    - run: ./dc restart web
    - run: sudo apt install libgbm-dev-lts-utopic
    - run:
        name: Install Node.js 10 and run cypress
        # https://www.cloudesire.com/how-to-upgrade-node-on-circleci-machine-executor/
        command: |
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install v10 && nvm use v10 && nvm alias default v10
          node -v
          curl -o- -L https://yarnpkg.com/install.sh | bash
          ~/.yarn/bin/yarn add cypress@6
          ~/.yarn/bin/yarn add cypress-file-upload
          ~/.yarn/bin/yarn cypress install
          ~/.yarn/bin/yarn cypress run
    - run:
        name: Deploy
        command: |
          ssh root@routechoices.com 'sudo -u apps /apps/routechoices.com/bin/deploy'
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots
workflows:
  build:
    jobs:
    - build
  version: 2
