version: '2'  
services:
  db:
    container_name: rc_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"
  minio:
    container_name: rc_minio
    image: minio/minio:edge
    volumes:
      - ../media:/data
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command:
      - server
      - /data
  smtp:
    container_name: rc_mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    expose:
      - "1025"
  nginx:
    container_name: rc_nginx
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ../:/app/
      - ../nginx:/etc/nginx/conf.d
    links:
      - minio
      - django
  django:
    container_name: rc_django
    image: rphl/routechoices-dev-server
    stop_signal: SIGINT
    volumes:
      - ../:/app/:rw
    environment:
      DATABASE_URL: postgres://app_user:changeme@db/app_db
    ports:
      - "8000:8000"
      - "2000:2000"
      - "2002:2002"
    expose:
      - "8000"
      - "2000"
      - "2002"
    links:
      - db
      - minio
      - smtp
    user: ${USERID}:${GROUPID}
